version: 2.1

jobs:
  build:
    macos:
      xcode: 11.3.0
    working_directory: ~/seamlesspay-ios
    steps:
      - checkout
      - run: 
          name: Prepare schema
          command: |
            cd Example/
            pwd
            sed -i xcscheme 's/TEST_SECRET_KEY/${TEST_SECRET_KEY}/g' ./SeamlessPayCore.xcodeproj/xcshareddata/xcschemes/CISeamlessPayCoreTests.xcscheme
            sed -i xcscheme 's/TEST_PUBLIC_KEY/${TEST_PUBLIC_KEY}/g' ./SeamlessPayCore.xcodeproj/xcshareddata/xcschemes/CISeamlessPayCoreTests.xcscheme
            cat ./SeamlessPayCore.xcodeproj/xcshareddata/xcschemes/CISeamlessPayCoreTests.xcscheme
      - run:
          name: Build app for testing 
          command: |
            cd Example/ 
            xcodebuild build-for-testing -workspace SeamlessPayCore.xcworkspace -scheme CISeamlessPayCoreTests -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.3'
      - run: 
          name: Run tests
          command: |
            cd Example/ 
            xcodebuild test -workspace SeamlessPayCore.xcworkspace -scheme CISeamlessPayCoreTests -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.3'  
